<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);IDE0130;IDE0290;CA1859</NoWarn>
    <RootNamespace>GarageGroup.Infra</RootNamespace>
    <AssemblyName>GarageGroup.Infra.Endpoint.Core</AssemblyName>
    <Version>1.1.0-build.5</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../contract/Endpoint.Contract/Endpoint.Contract.csproj" />
    <ProjectReference Include="../Endpoint.Generator/Endpoint.Generator.csproj">
      <PrivateAssets>contentfiles; build</PrivateAssets>
      <SetTargetFramework>TargetFramework=netstandard2.0</SetTargetFramework>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
    <PackageReference Include="Microsoft.OpenApi" Version="3.5.5" />
    <PackageReference Include="PrimeFuncPack.Core.Failure" Version="2.2.0" />
    <PackageReference Include="PrimeFuncPack.Core.Optional" Version="2.1.0" />
    <PackageReference Include="PrimeFuncPack.Core.Result" Version="2.0.2" />
  </ItemGroup>

</Project>