name: .NET

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

     # Add NuGet Sources

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    - name: Add GarageGroup NuGet Source
      run: >
        dotnet nuget add source ${{ vars.GG_NUGET_SOURCE_URL }}
        -n garage
        -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }}
        -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --store-password-in-clear-text

    # Endpoint.Generator

    - name: Restore Endpoint.Generator
      run: dotnet restore ./src/*/Endpoint.Generator.csproj

    - name: Build Endpoint.Generator
      run: dotnet build ./src/*/Endpoint.Generator.csproj --no-restore  -c Release

    - name: Pack Endpoint.Generator
      run: dotnet pack ./src/*/Endpoint.Generator.csproj --no-restore -o ~/nuget  -c Release

    # Endpoint.Annotation

    - name: Restore Endpoint.Annotation
      run: dotnet restore ./src/*/Endpoint.Annotation.csproj

    - name: Build Endpoint.Annotation
      run: dotnet build ./src/*/Endpoint.Annotation.csproj --no-restore  -c Release

    - name: Pack Endpoint.Annotation
      run: dotnet pack ./src/*/Endpoint.Annotation.csproj --no-restore -o ~/nuget  -c Release

    # Endpoint.Core

    - name: Restore Endpoint.Core
      run: dotnet restore ./src/*/Endpoint.Core.csproj

    - name: Build Endpoint.Core
      run: dotnet build ./src/*/Endpoint.Core.csproj --no-restore  -c Release

    - name: Pack Endpoint.Core
      run: dotnet pack ./src/*/Endpoint.Core.csproj --no-restore -o ~/nuget  -c Release

    # Endpoint.AspNetCore.Generator

    - name: Restore Endpoint.AspNetCore.Generator
      run: dotnet restore ./src/*/Endpoint.AspNetCore.Generator.csproj

    - name: Build Endpoint.AspNetCore.Generator
      run: dotnet build ./src/*/Endpoint.AspNetCore.Generator.csproj --no-restore  -c Release

    - name: Pack Endpoint.AspNetCore.Generator
      run: dotnet pack ./src/*/Endpoint.AspNetCore.Generator.csproj --no-restore -o ~/nuget  -c Release

    # Endpoint.AspNetCore

    - name: Restore Endpoint.AspNetCore
      run: dotnet restore ./src/*/Endpoint.AspNetCore.csproj

    - name: Build Endpoint.AspNetCore
      run: dotnet build ./src/*/Endpoint.AspNetCore.csproj --no-restore  -c Release

    - name: Pack Endpoint.AspNetCore
      run: dotnet pack ./src/*/Endpoint.AspNetCore.csproj --no-restore -o ~/nuget  -c Release

    # Endpoint.SchemaProvider

    - name: Restore Endpoint.SchemaProvider
      run: dotnet restore ./src/*/Endpoint.SchemaProvider.csproj

    - name: Build Endpoint.SchemaProvider
      run: dotnet build ./src/*/Endpoint.SchemaProvider.csproj --no-restore  -c Release

    - name: Pack Endpoint.SchemaProvider
      run: dotnet pack ./src/*/Endpoint.SchemaProvider.csproj --no-restore -o ~/nuget  -c Release

    # Endpoint.TypeParser

    - name: Restore Endpoint.TypeParser
      run: dotnet restore ./src/*/Endpoint.TypeParser.csproj

    - name: Build Endpoint.TypeParser
      run: dotnet build ./src/*/Endpoint.TypeParser.csproj --no-restore  -c Release

    - name: Pack Endpoint.TypeParser
      run: dotnet pack ./src/*/Endpoint.TypeParser.csproj --no-restore -o ~/nuget  -c Release

    # Push

    - name: Push Packages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: >
        dotnet nuget push "../../../nuget/*.nupkg"
        -s ${{ vars.GG_NUGET_SOURCE_URL }}
        -k ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --skip-duplicate
